language: node_js
node_js:
- lts/*
cache:
  yarn: true
  directories:
  - node_modules
script:
    - yarn test
    - yarn build
deploy:
  provider: firebase
  local_dir: build
env:
  global:
  - secure: CGVcgdy80OytshBOfA7L2S7q4V1YyjcWgEdMs8fEBDzyPTFhl7i38/rM8pv9oFa3L5e0Wsyjmn09N8knQOP7Jjj52z4mk1auuV/YlmE3kHT39ScDycDUHWB6S2AEi6+3MMWb053tibzyQ09WSy0ix7gD8m6tML3sGx2kjrwbWJ+jOEAlmSQnOiK0KzOTGzuJdOv8xdAU7VkuIRapceZmPOoIZ0m88n1TgHa3reap12lA7YJjPt8z+EMOE5exrNNrXrPimC2or7wQSFkBwFN1XZZJQunCFbO7S0R3kbSYWlkrHSSD9Nlo1bXHH+WVe4rhX4gypE/Yb+kvXxbOJ0UUncYXxtKAqMcgM9FHbKGRE0RPD3cPfbpcwUdB/pCqHeDwwMuh2fhbOLUf+eOvr6E0mIoHHnxyIP5UVPE+D2PdYsY9YEhxmAt7ROhTPRTMyz6jqKat/ayyFnbg55oVzJAu+7ZwguKvj1UsY3c5+gYn08cg7vq6lqFcNtWWDS5HUL0NLwbSENzJtcIo9K9A1XNlV+eL2Veq2yXkYktD1G4ODcpkV8cJTRkWFXmJqsOMi3Jwykf6ac3Pd1ItC5EfNycG20SzGe7Et1CsWkrsp61ZuURMdgmC+Zo2Gho5GsXiwltvdJFLf1Sm/NG1YGDd7b1gliU5w0YO4ryWN3LVo3nncsA=
