language: node_js
node_js:
- lts/*
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn test
- yarn build
deploy:
  provider: firebase
  local_dir: build
env:
  global:
    secure: HSvB7/nqgU+Xexx2tgsSa9ZYgC3KBOxovlAD3ZMUd9iSNbA7fFk7CokEiqn1LSYMXHdcw6zD9/MJUI036+4X6/+L6BRvFc9NmgrdkSJyAi8jaNfODfMyGif794xEh9SpwyTbyIuTNeb86yoRSQTTaqWLs8pqWmh8zkHA43M8nGNIz+a7glqPtjToNckh2cacXZebGM8FgOhr5PQvWtLCWasqTw3jLpw3anI69VDfsA6nBjIkqDZWIuvD1QMJKI+BFJ+K0RGDiRrYSx/iijVUPqzTOMq0dGdZGx+ojxpoek9BSDQPB6J5z9ZjZO41A/Tamji8fuApgGMk5DnwXjl2wAJkrJpOwb5I7OiKtnXAa/YiK3IaqnOPKtV8kpKIeP+StkmyebjWTcqGj5fYoMbTmQV/tsUuYL5JuWYepq1ANhKI3ebHp7mqR3mheJFs/L5jn3SepWSph8SLSBbOaP5dBbuP2MuxFfSpxf6VQKybp/U664qT6P1dgFudi5tYJIumqP7E0oBdoTeLYG4XZcygbw359NWjqtDPzoJaYsCCnbxmm5WrHQ2unZEENLoU56NLjFwKYowQCUt7mM5hi0HDrJix+onlD8BBHX1XWy7a4psvCCgjnshvWg59AnQe/0oH1Pjgr/IQVZW07QHbaJQNekSu5BmLAP3HbDGouSW5RGY=
